[package]
name = "bzip2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cbindgen = "0.20.0"
clap = { version = "3.1.1", features = ["derive"] }
